id: AA42529ED
title: Calling the Guru from Afar
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:36:36.530982
  last_modified_at: 2022-03-01 01:36:36.530986
