id: AA42529ED
title: A Prayer for the Swift Return of the Fourth Kyabje Dodrupchen Rinpoche
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:36:36.520564
  last_modified_at: 2022-03-01 01:36:36.520571
