id: AA42529ED
title: 'The Beat of the Vajra Drum: A Prayer'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:36:36.534870
  last_modified_at: 2022-03-01 01:36:36.534873
