id: AA42529ED
title: 'The Lotus of Faith: A Supplication to the Successive Lives of Shechen Rabjam'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:36:36.537332
  last_modified_at: 2022-03-01 01:36:36.537335
