id: AA42529ED
title: A Prayer to Kyabje Dilgo Khyentse Rinpoche
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:36:36.525531
  last_modified_at: 2022-03-01 01:36:36.525536
